load("//arvr/tools/build_defs:oxx.bzl", "oxx_static_library")

oxx_static_library(
    name = "chess_codec",
    srcs = ["ChessCodec.cpp"],
    ovrsource_only = False,
    public_include_directories = [
        "../../../..",
    ],
    public_raw_headers = ["ChessCodec.h"],
    raw_headers = ["ChessCodec.h"],
    visibility = ["PUBLIC"],
    deps = [
        "//arvr/libraries/logging:logging",
        "//arvr/libraries/vrs/vrs:vrs",
        "//arvr/libraries/vrs/vrs/utils:images",
    ],
)
