name: Publish Python package to test.pypi.org

on:
  # run every day at 2:30 PST
  schedule:
    - cron: '30 10 * * *'

jobs:
  build-bin-macos:
    if: github.repository == 'facebookresearch/vrs'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          brew install ninja cmake ccache googletest glog fmt cereal \
            jpeg-turbo libpng \
            lz4 zstd xxhash \
            boost \
            portaudio pybind11

      - name: Install python dependencies
        run: |
          pip install -U pip
          pip install numpy typing dataclasses pytest parameterized Pillow
          pip install --upgrade build setuptools setuptools_scm wheel

      - name: Build packages (wheel and source distribution)
        run: |
          python -m build --sdist --wheel --outdir dist/ pyvrs
          ls -l dist
      - name: Store the binary wheel
        uses: actions/upload-artifact@v2
        with:
          name: python-package-distributions
          path: dist

  build-bin-linux:
    if: github.repository == 'facebookresearch/vrs'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install -o Acquire::Retries=5 \
            cmake ninja-build ccache libgtest-dev libfmt-dev libcereal-dev \
            libturbojpeg-dev libpng-dev \
            liblz4-dev libzstd-dev libxxhash-dev \
            libboost-system-dev libboost-filesystem-dev libboost-thread-dev libboost-chrono-dev libboost-date-time-dev \
            portaudio19-dev
      - name: Install python dependencies
        run: |
          pip install -U pip
          pip install pybind11[global]
          pip install numpy typing dataclasses pytest parameterized Pillow
          pip install --upgrade build setuptools setuptools_scm wheel

      - name: Build packages (wheel and source distribution)
        run: |
          python -m build --sdist --wheel --outdir dist/ pyvrs
          ls -l dist
      - name: Store the binary wheel
        uses: actions/upload-artifact@v2
        with:
          name: python-package-distributions
          path: dist
  deploy:
    needs:
    - build-bin-macos
    - build-bin-linux
    runs-on: ubuntu-20.04

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v2
        with:
          name: python-package-distributions
          path: dist/
      - name: Deploy to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
          verbose: true
